#Spring configuration
spring:
  data:
    mongodb:
      host: ${MONGO_HOST:}
      database: ${MONGO_DB:medicapp}
      username: ${MONGO_USER:}
      password: ${MONGO_PASS:}
      authentication-database: ${MONGO_AUTH_DB:admin}
      auto-index-creation: ${MONGO_AUTO_INDEX:false}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USER:}
    password: ${MAIL_PASS:}
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true
api:
  positionStack:
    uri: ${POSITIONSTACK_API_URI:}
    key: ${POSITIONSTACK_API_KEY:}
#Server configuration
#server:
#  port: 443
#  ssl:
#    key-store: classpath:medicapp.p12
#    key-store-password: medicapp
#    key-store-type: PKCS12
#  error:
#    whitelabel:
#      enabled: false

#Log configuration
logging:
  level:
    root: ${LOG_LEVEL_ROOT:info}
    org.springframework.data.mongodb.core.MongoTemplate: ${LOG_LEVEL_MONGO:debug}
#  pattern:
#    console: '${CONSOLE_LOG_PATTERN:-%clr(%d{dd-MM-yyyy HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}'
