#Spring configuration
spring:
  security:
    oauth:
      client.id: medicapp
      client.secret: 12345
      jwt.secretkey: codigosupersecreto
  data:
    mongodb:
      host: localhost
      authentication-database: admin
      database: test
      username: medicapp
      password: medicapp1
  mail:
    host: smtp.gmail.com
    port: 587
    username: fe.neiraj@gmail.com
    password: lbijxnkpoddlyoji
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true
#  redis:
#    host: localhost
#    port: 6379
#    ssl: true
#    password: 57686f6120447564652c2049495320526f636b73


#Log configuration
logging:
  level:
    root: info
    org.hibernate.SQL: info
    org.springframework.data.mongodb.core.MongoTemplate: info
#  pattern:
#    console: '${CONSOLE_LOG_PATTERN:-%clr(%d{dd-MM-yyyy HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}'