#Application security config
security:
  auth:
    client:
      id: medicapp
      secret: 12345
    jwt:
      secretKey: codigosupersecreto
  config:
    accessTokenValiditySeconds: 10000
    authorizedGrantTypes: >
      password,
      refresh_token
    scopes: >
      read,
      write